package rtp;

/**
 * Created by javig on 03/07/2017.
 */
public interface CSVHeaders {
    String CLASS_VERSIO = "DATA;";
    String CLASS_OPERADOR = "OPERADOR_ID;OPERADOR_NOM_CURT;OPERADOR_NOM_CURT_PUBLIC;OPERADOR_NOM_COMPLET_PUBLIC;";
    String CLASS_PARADA = "PARADA_PUNT_ID;PARADA_PUNT_DESC;PARADA_PUNT_DESC_CURTA;COORD_X;COORD_Y;PARADA_ID;MUNICIPI_ID;";
    String CLASS_LINIA = "LINIA_ID;LINIA_NOM_CURT;LINIA_DESC;OPERADOR_ID;MODE_TRANSPORT";
    String CLASS_EXPEDICIO = "PERIODE_ID;EXPEDICIO_ID;LINIA_ID;TRAJECTE_ID;DIRECCIO_ID;EXPEDICIO_ID_IMPRESSIO;SORTIDA_HORA;DIA_ATRIBUT_ID;NOTA_ID;BICICLETA_SN;TIPUS_VEHICLE_ID;GRUP_HORARI_ID;RESTRICCIO_ID;SORTIDA_PARADA_PUNT_ID;ARRIBADA_PARADA_PUNT_ID;";
    String CLASS_RESTRICCIO = "PERIODE_ID; RESTRICCIO_ID;DESC1;DESC2;DESC3;DESC4;DESC5;DIES;";
    String CLASS_PERIODE = "PERIODE_ID;PERIODE_DESC;PERIODE_DINICI;PERIODE_DFI;";
    String CLASS_ITINERARI = "LINIA_ID;TRAJECTE_ID;DIRECCIO_ID;SEQUENCIA_ID;PARADA_PUNT_ID;DISTANCIA;PARADA_PUNT_TIPUS;";
    String CLASS_VEHICLE = "TIPUS_VEHICLE_ID;VEHICLE_DESC;N_SEIENTS;N_PASS_DRETS;N_CADIRA_RODES;ELEVADOR_SN;PLATAFORMA_SN;";
    String CLASS_TEMPS_ITINERARI = "LINIA_ID;TRAJECTE_ID;DIRECCIO_ID;SEQUENCIA_ID;GRUP_HORARI_ID;TEMPS_VIATGE;TEMPS_PARAT";
    String CLASS_TRAJECTE = "LINIA_ID;TRAJECTE_ID;DIRECCIO_ID;TRAJECTE_DESC;";
}
